Historyvalidation
hhru-school/contracts-tests-admin pull request #136
Opened 2023-05-23 13:10 UTC by SerDImIgor

Создал страницу история валидация. Прошу посмотреть и оставить замечания

2023-05-23 16:56 UTC, GavrilenkoValentine requested changes
В целом хорошо, но есть несколько важных замечаний.

2023-05-23 16:56 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/index.tsx
> +        standName ? `/api/stands/${standName.standName}/validations` : null,
Сюда нужно добавить квери параметр `sizeLimit` для отображения нескольких последних валидаций

2023-05-23 16:56 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/index.tsx
> +    const filteredData = data.slice(0, 5);
Если вынести логику показа последних валидаций в квери параметр выше, то это можно убрать

2023-05-23 16:56 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/index.tsx
> +        return null;
С такой логикой у нас будет пустая колонка вместо истории валидаций.
Нужно либо убирать компонент совсем либо писать сообщение, что валидаций нет.

![image](https://github.com/hhru-school/contracts-tests-admin/assets/39316843/1f43fc96-8878-4101-8f97-ef6aec9a7e67)

2023-05-23 16:56 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/index.tsx
> +                    <div className="justify-content-start">
Класс `justify-content-start` тут не нужен.
Кроме того, компонент `CardText` нужен для отображения текста, т.к. отрисовывает `<p>` тэг. Помещать в него блоки - плохая практика. Попробуй сделать список как в [этом](https://reactstrap.github.io/?path=/docs/components-card--card#kitchen-sink) примере

2023-05-23 16:56 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/index.tsx
>  import { Nav, NavItem, NavLink } from 'reactstrap';
Чтобы работал SPA роутинг без перезагрузки страницы, нужно использовать `NavLink` из `react-router-dom`, а не из `reactstrap`

2023-05-23 16:56 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/types.tsx
> +export type standResponce = {
Мистайп, должно быть `StandResponse`, кроме того названия типов мы пишем с большой буквы

2023-05-23 16:56 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/types.tsx
> +    status: string;
Возможно, нужно заменить на `enum`, т.к. мы точно знаем все возможные варианты статусов

2023-05-23 16:56 UTC, GavrilenkoValentine commented on frontend/src/routes/index.tsx
> +    { path: '/validations', element: <Navigate to={navigation.validations} replace /> },
Этот кусок не нужно было дублировать. Достаточно добавить еще один элемент в массив `children` после `StatusesPage`.

2023-05-23 16:56 UTC, GavrilenkoValentine commented on frontend/src/pages/Validations/index.tsx
> +        return null;
С такой логикой пользователь будет видеть пустую страницу если у стенда еще нет валидаций.
Нужно бы добавить какое-нибудь сообщение-заглушку.

2023-05-23 16:56 UTC, GavrilenkoValentine commented on frontend/src/pages/Validations/index.tsx
> +                {!standName && <h5>выберите стенд для отображения сервисов</h5>}
Похоже, ты скопировал это сообщение из страницы статусов, но забыл его поменять текст

2023-05-23 16:56 UTC, GavrilenkoValentine commented on frontend/src/pages/Validations/index.tsx
> +                <Row>
Для консистентности общего вида здесь лучше обернуть все в `ListGroup` и внутри отрисовывать `ListGroupItem`, как на странице статуса.

2023-05-24 07:27 UTC, SerDImIgor commented on frontend/src/components/ValidationHistory/index.tsx
> +        standName ? `/api/stands/${standName.standName}/validations` : null,
Я уже попросил беков

2023-05-24 07:29 UTC, SerDImIgor commented on frontend/src/components/ValidationHistory/index.tsx
> +    const filteredData = data.slice(0, 5);
Попросил беков доработать ручку

2023-05-24 08:28 UTC, SerDImIgor commented on frontend/src/components/ValidationHistory/index.tsx
> +                    <div className="justify-content-start">
Поправил

2023-05-24 08:28 UTC, SerDImIgor commented on frontend/src/components/ValidationHistory/index.tsx
>  import { Nav, NavItem, NavLink } from 'reactstrap';
Исправил !

2023-05-24 08:32 UTC, SerDImIgor commented on frontend/src/components/ValidationHistory/types.tsx
> +    status: string;
Спрошу перечень статусов у бека

2023-05-24 08:34 UTC, SerDImIgor commented on frontend/src/routes/index.tsx
> +    { path: '/validations', element: <Navigate to={navigation.validations} replace /> },
ok

2023-05-24 08:39 UTC, SerDImIgor commented on frontend/src/pages/Validations/index.tsx
> +        return null;
Поправил !!!

2023-05-24 08:40 UTC, SerDImIgor commented on frontend/src/pages/Validations/index.tsx
> +                {!standName && <h5>выберите стенд для отображения сервисов</h5>}
Точно )

2023-05-24 09:23 UTC, SerDImIgor commented on frontend/src/pages/Validations/index.tsx
> +                <Row>
Сделал !!

2023-05-24 09:32 UTC, SerDImIgor commented on frontend/src/pages/Validations/index.tsx
> +                <Row>
Поправил

2023-05-24 09:36 UTC, SerDImIgor commented on frontend/src/components/ValidationHistory/index.tsx
>  import { Nav, NavItem, NavLink } from 'reactstrap';
Ok

2023-05-24 09:39 UTC, SerDImIgor commented on frontend/src/components/ValidationHistory/types.tsx
> +    status: string;
Сделал

2023-05-24 09:39 UTC, SerDImIgor commented on frontend/src/routes/index.tsx
> +    { path: '/validations', element: <Navigate to={navigation.validations} replace /> },
Исправил

2023-05-24 10:25 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/index.tsx
> +    const filteredData = data.slice(0, 5);
Ручка есть и квери параметр такой тоже есть

2023-05-24 10:27 UTC, GavrilenkoValentine commented on frontend/src/routes/index.tsx
> +    { path: '/validations', element: <Navigate to={navigation.validations} replace /> },
Поменяй расширение файла на `.ts`, чтобы его jsx не обрабатывал

2023-05-24 10:27 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/types.tsx
> +    status: string;
Поменяй расширение файла на `.ts`, чтобы его jsx не обрабатывал

2023-05-24 10:37 UTC, SerDImIgor commented on frontend/src/components/ValidationHistory/index.tsx
> +    const filteredData = data.slice(0, 5);
Да, я это убрал

2023-05-24 10:38 UTC, SerDImIgor commented on frontend/src/components/ValidationHistory/types.tsx
> +    status: string;
Ok

2023-05-24 10:45 UTC, GavrilenkoValentine requested changes
Оставил несколько мелких замечаний

2023-05-24 10:45 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/index.tsx
> +                <h5>Выберите стенд для отображения валидации</h5>
Заголовок слишком большой для этого компонента. Лучше использовать что-то типа `<p>` или `<small>`

2023-05-24 10:45 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/index.tsx
> +                <h5>Нет валидаций для стенда({standName})</h5>
Заголовок слишком большой для этого компонента. Лучше использовать что-то типа `<p>` или `<small>`

2023-05-24 10:45 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/index.tsx
> +                <CardText>
Этот компонент-обертка тут лишний. Кроме того, он оборачивает контент в `<p>`, а у нас там блоки со списком.

2023-05-24 10:45 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/types.tsx
> +export enum Direction {
Поменяй формат файла на `.ts`, чтобы его не обрабатывал jsx

2023-05-24 10:45 UTC, GavrilenkoValentine commented on frontend/src/components/ValidationHistory/index.tsx
> +export const ValidationHistory: React.FC<ServicesContainerProps> = ({ standName, sizeLimit }) => {
Хорошее решение с пропом `sizelimit`, но я бы предложил сделать дефолтное значение в случае если он отсутствует в пропсах. Например - 5

2023-05-24 10:45 UTC, GavrilenkoValentine commented on frontend/src/pages/Statuses/index.tsx
> +                <ValidationHistory standName={standName} sizeLimit={5} />
Если сделать `sizeLimit` дефолтным внутри компонента, то отсюда его можно убрать

2023-05-24 10:45 UTC, GavrilenkoValentine commented on frontend/src/pages/Validations/index.tsx
> +                <ListGroupItem>
Тут забыл проп  `key` для элементов списка. В консоли react тебе об этом напоминает

2023-05-24 10:45 UTC, GavrilenkoValentine commented on frontend/src/routes/index.tsx
> +                index: true,
Свойство `index` тут не нужно

2023-05-24 10:45 UTC, GavrilenkoValentine commented on frontend/src/routes/index.tsx
> +                path: 'validations',
Лучше использовать `path` из `navigation` констант

2023-05-24 19:32 UTC, GavrilenkoValentine approved these changes

2023-05-24 19:33 UTC, merged