HH-129 бизнес логика получения связей продюсер консьюмер
hhru-school/contracts-tests-admin pull request #149
Opened 2023-06-03 22:13 UTC by Ziyakaev

have implements validation service relations logic

2023-06-07 07:58 UTC, omjustnikova requested changes

2023-06-07 07:58 UTC, omjustnikova commented on db/db.sql
>      validation_id               BIGINT GENERATED ALWAYS AS IDENTITY not null,
Тут можно было бы просто назвать id, так как таблица validation, то и понятно, что validation.id, а не задублированное validation.validation_id. Ну и к остальным колонкам такая же методика. Можно не менять сейчас, на будущее просто.

2023-06-07 08:08 UTC, aziiakaev commented on db/db.sql
>      validation_id               BIGINT GENERATED ALWAYS AS IDENTITY not null,
в моем случае можно использовать LEFT JOIN USING, что кажется удобным

2023-06-07 08:15 UTC, Ziyakaev commented on app/src/main/java/com/hh/contractstestsadmin/service/ServiceRelationMapper.java
> +    servicesRelationDto.setErrorCount(serviceRelation.getCountOfError());
поправил

2023-06-07 08:21 UTC, Ziyakaev commented on app/src/main/java/com/hh/contractstestsadmin/dto/api/ConsumerMapper.java
> +package com.hh.contractstestsadmin.dto.api;
я уже в какой-то другой задаче создал пакет mapper. Ок, тут тоже создал перенес

2023-06-07 08:22 UTC, Ziyakaev commented on app/src/main/java/com/hh/contractstestsadmin/resource/ValidationResource.java
> +  @Path("stands/{standName}/validation/{validationId}")
поправил

2023-06-07 08:56 UTC, Ziyakaev commented on app/src/main/java/com/hh/contractstestsadmin/service/ServiceRelationMapper.java
> +  public static ServicesRelationDto map(ServiceRelation serviceRelation) {
поправил

2023-06-07 09:35 UTC, omjustnikova approved these changes

2023-06-07 09:35 UTC, omjustnikova commented on db/db.sql
>      validation_id               BIGINT GENERATED ALWAYS AS IDENTITY not null,
Все-таки, в этом месте хочу поспорит: это сродни объекту и свойствам, таблица - объект, колонки - свойства. При создании объекта же ты не называешь свойство validationId, а называешь id просто, потому что по названию объекта понятно id какого объекта.

2023-06-09 12:18 UTC, Ziyakaev commented on app/src/main/java/com/hh/contractstestsadmin/service/mapper/ValidationWithRelationsMapper.java
> +    ValidationWithRelationsDto validationMetaInfoDto = new ValidationWithRelationsDto(ValidationMapper.map(validation));
поправил

2023-06-09 12:49 UTC, Ziyakaev commented on app/src/main/java/com/hh/contractstestsadmin/resource/ValidationResource.java
> +      if (validationId == null || standName == null) {
поправил

2023-06-09 13:01 UTC, Ziyakaev commented on app/src/main/java/com/hh/contractstestsadmin/dto/api/ServiceDto.java
>  public class ServiceDto {
зачем для статуса мы используем ServiceStatusDto а для ошибок хотим именно со всем сервисом использовать, думаю можно переименовать если что. не может так как заполняется только или producer или consumer, можем для него отдельным enum придумать если очень хочется

2023-06-09 18:25 UTC, Ziyakaev commented on app/src/main/java/com/hh/contractstestsadmin/service/mapper/ServiceMapper.java
> +  public static ServiceDto map(Service service, String fileLink, ServiceType serviceType) {
удалил класс

2023-06-09 18:26 UTC, Ziyakaev commented on app/src/main/java/com/hh/contractstestsadmin/dto/api/ServiceDto.java
>  public class ServiceDto {
поправил

2023-06-09 21:40 UTC, RealBaty approved these changes

2023-06-09 21:40 UTC, RealBaty commented on app/src/main/java/com/hh/contractstestsadmin/dto/api/ServicesRelationDto.java
> +  public ServiceDto getProducer() {
Тут должно ProducerDto возвращаться

2023-06-10 10:11 UTC, merged