Business logic for stands list
hhru-school/contracts-tests-admin pull request #77
Opened 2023-04-25 12:25 UTC by RealBaty

2023-04-25 14:51 UTC, omjustnikova requested changes

2023-04-25 14:51 UTC, omjustnikova commented on app/src/main/java/com/hh/contractstestsadmin/config/AppConfig.java
> +  @Value("${release.name}")
Я бы назвала свойство "release.stand.name" - имя релизного стенда, более точно бы суть отражало. И переменную тоже releaseStandName

2023-04-25 14:51 UTC, omjustnikova commented on app/src/main/java/com/hh/contractstestsadmin/config/AppConfig.java
> +    return statusService;
contractsDao - это Bean, предлагаю его вндерять с помощью @Inject, releaseName сделать тоже бином, также его внедрить, а от конструктора и сетера избавиться в StatusService.

2023-04-26 08:42 UTC, RealBaty commented on app/src/main/java/com/hh/contractstestsadmin/config/AppConfig.java
> -  public StatusService statusService(){
Готово

2023-04-26 08:42 UTC, RealBaty commented on app/src/main/java/com/hh/contractstestsadmin/config/AppConfig.java
> +  @Value("${release.name}")
Готово

2023-04-26 08:48 UTC, RealBaty commented on app/src/main/java/com/hh/contractstestsadmin/config/AppConfig.java
> +    return statusService;
Не очень понятно как ты хочешь releaseName сделать бином. StatusService нужно сделать бином, а так как нам не желательно пользоваться спринговыми анотациями, я его объявил через конфиг. К тому же не получится избавится от конструктора используя аннотацию Inject (Внедрять зависимости все же надо либо через сеттер либо через конструктор)

2023-04-26 10:34 UTC, omjustnikova commented on app/src/main/java/com/hh/contractstestsadmin/config/AppConfig.java
> +    return statusService;
Решили изучить это вопрос подробнее, а пока внедрить  зависимости через конструкто.

2023-04-26 10:59 UTC, RealBaty commented on app/src/main/java/com/hh/contractstestsadmin/config/AppConfig.java
> +    return statusService;
Убрал сеттер, теперь все через конструктор

2023-04-26 11:18 UTC, omjustnikova commented on app/src/main/java/com/hh/contractstestsadmin/exception/StandNotFoundException.java
>  public class StandNotFoundException extends NotFoundException {
Этот файл нуждается все еще в автоформатировании.

2023-04-26 11:39 UTC, RealBaty commented on app/src/main/java/com/hh/contractstestsadmin/exception/StandNotFoundException.java
>  public class StandNotFoundException extends NotFoundException {
Готово

2023-04-27 08:45 UTC, omjustnikova approved these changes

2023-04-27 09:23 UTC, merged