Refactor stand services endpoint
hhru-school/contracts-tests-admin pull request #83
Opened 2023-04-28 13:36 UTC by RealBaty

Новая схема данных:
```
{
  "releaseName": "release",
  "releaseLink": "release_version",
  "stands": [
    {
      "name": "stand1",
      "standServices": [
        {
          "name" : "service1",
          "version": "service_version",
          "isConsumer": true,
          "expectationLink": "https://*",
          "expectationPublishDate": "2023-04-10T17:19:11.503988200Z",
          "isProducer": true,
          "schemaLink": "https://*",
          "schemaPublishDate": "2023-04-10T17:19:11.503988200Z"
        }
      ],
      "releaseServices": [
        {
          "name" : "service1",
          "version": "service_version",
          "isConsumer": true,
          "expectationLink": "https://*",
          "expectationPublishDate": "2023-04-10T17:19:11.503988200Z",
          "isProducer": true,
          "schemaLink": "https://*",
          "schemaPublishDate": "2023-04-10T17:19:11.503988200Z"
        }
      ],
      "validationHistory": [
        {
          "id": 1,
          "date": "2023-04-10T17:19:11.503988200Z",
          "releaseLink": "release_version",
          "status": "SUCCESS/FAILED/IN_PROGRESS/CANCELLED",
          "errorCount": 4
        }
      ]
    }
  ]
}
```
Измененная ручка:
Получить метаинформацию о сервисах с определенного стенда (сервисы отсортированы по имени)

> запрос: `GET /api/services`
> QueryParam: standName (имя стенда с которого нужно получить метаинформацию о сервисах) 
> Статус: 200
> возвращаемая структура:
> ```
> {
>   "standServices": [
>         {
>           "name" : "service1",
>           "version": "service_version",
>           "isConsumer": true,
>           "expectationLink": "https://*",
>           "expectationPublishDate": "2023-04-10T17:19:11.503988200Z",
>           "isProducer": true,
>           "schemaLink": "https://*",
>           "schemaPublishDate": "2023-04-10T17:19:11.503988200Z"
>         }
>    ],
>    "releaseServices": [
>         {
>           "name" : "service1",
>           "version": "service_version",
>           "isConsumer": true,
>           "expectationLink": "https://*",
>           "expectationPublishDate": "2023-04-10T17:19:11.503988200Z",
>           "isProducer": true,
>           "schemaLink": "https://*",
>           "schemaPublishDate": "2023-04-10T17:19:11.503988200Z"
>         }
>    ]
> }
> ```
> В случае если стенда не существует: 404
> В случае если standName не задан: 400

2023-04-30 15:35 UTC, RealBaty commented
Изменил ручку, теперь запрос следующий:
`GET /api/stand/{standName}/services`

2023-05-01 04:17 UTC, omjustnikova requested changes

2023-05-01 04:17 UTC, omjustnikova commented on app/src/main/java/com/hh/contractstestsadmin/service/StatusService.java
>  import com.fasterxml.jackson.core.type.TypeReference;
У меня нет замечаний, кроме одного архитектурного: а по какому эндпоинту будут получаться сервисы релизного стенда, в случае, если пользователь захочет только их?

2023-05-01 07:13 UTC, Ziyakaev approved these changes

2023-05-01 14:45 UTC, RealBaty commented
Изменил API. Новая схема данных:
```
{
  "stands": [
    {
      "name": "stand1",
      "isRelease": false,
      "releaseLink": "release_version",
      "standServices": [
        {
          "name" : "service1",
          "version": "service_version",
          "isConsumer": true,
          "expectationLink": "https://*",
          "expectationPublishDate": "2023-04-10T17:19:11.503988200Z",
          "isProducer": true,
          "schemaLink": "https://*",
          "schemaPublishDate": "2023-04-10T17:19:11.503988200Z"
        }
      ],
      "releaseServices": [
        {
          "name" : "service1",
          "version": "service_version",
          "isConsumer": true,
          "expectationLink": "https://*",
          "expectationPublishDate": "2023-04-10T17:19:11.503988200Z",
          "isProducer": true,
          "schemaLink": "https://*",
          "schemaPublishDate": "2023-04-10T17:19:11.503988200Z"
        }
      ],
      "validationHistory": [
        {
          "id": 1,
          "date": "2023-04-10T17:19:11.503988200Z",
          "releaseLink": "release_version",
          "status": "SUCCESS/FAILED/IN_PROGRESS/CANCELLED",
          "errorCount": 4
        }
      ]
    }
  ]
}
```
Новые ручки:
1. Получить информацию о всех стендах (стенды отсортированы по имени)

> запрос: `GET /api/stands`
> Статус: 200
> возвращаемая структура:
> ```
>  [
>     {
>       "name": "stand1",
>       "isRelease": false
>     }
>  ]
> ```

2. Получить информацию о статусе стенда:

> запрос: `GET /api/stands/{standName}`
> PathParam: standName (имя стенда с которого нужно получить метаинформацию о сервисах) 
> Статус: 200
> возвращаемая структура:
> ```
>     {
>       "isRelease": false,
>       "releaseLink": "release_version",
>       "standServices": [
>         {
>           "name" : "service1",
>           "version": "service_version",
>           "isConsumer": true,
>           "expectationLink": "https://*",
>           "expectationPublishDate": "2023-04-10T17:19:11.503988200Z",
>           "isProducer": true,
>           "schemaLink": "https://*",
>           "schemaPublishDate": "2023-04-10T17:19:11.503988200Z"
>         }
>       ],
>       "releaseServices": [
>         {
>           "name" : "service1",
>           "version": "service_version",
>           "isConsumer": true,
>           "expectationLink": "https://*",
>           "expectationPublishDate": "2023-04-10T17:19:11.503988200Z",
>           "isProducer": true,
>           "schemaLink": "https://*",
>           "schemaPublishDate": "2023-04-10T17:19:11.503988200Z"
>         }
>       ],
>       "validationHistory": [
>         {
>           "id": 1,
>           "date": "2023-04-10T17:19:11.503988200Z",
>           "releaseLink": "release_version",
>           "status": "SUCCESS/FAILED/IN_PROGRESS/CANCELLED",
>           "errorCount": 4
>         }
>       ]
>     }
> ```
> В случае если стенда не существует: 404

3. Получить историю валидаций (валидации отсортированы по дате)

> запрос: `GET /api/stand/{{standName}}/validations`
> QueryParam: sizeLimit (максимальное число возвращаемых валидаций) 
> Статус: 200
> возвращаемая структура: 
> ```
> [
>       {
>         "id": 1,
>         "date": "2023-04-10T17:19:11.503988200Z",
>         "releaseLink": "release_version",
>         "status": "PASSED/FAILED/IN_PROGRESS/RUN_ERROR",
>         "errorCount": 4,
>       }
> ]
> ```
> В случае если стенда не существует: 404

4. Запустить валидацию

> запрос: `POST /api/stand/{{standName}}/validations`
> Статус: 202
> В случае если стенда не существует: 404

2023-05-01 15:30 UTC, omjustnikova commented on app/src/main/java/com/hh/contractstestsadmin/service/StatusService.java
>  import com.fasterxml.jackson.core.type.TypeReference;
Разобрались, что для релизного список сервисов стенда будет пустой.

2023-05-01 15:37 UTC, omjustnikova approved these changes

2023-05-03 12:52 UTC, RealBaty commented
Изменил API. Новая схема данных:
```
{
  "stands": [
    {
      "name": "stand1",
      "isRelease": false,
      "releaseLink": "release_version",
      "services": {
        "stand": [
          {
            "name": "service1",
            "version": "service_version",
            "isConsumer": true,
            "expectationLink": "https://*",
            "expectationPublishDate": "2023-04-10T17:19:11.503988200Z",
            "isProducer": true,
            "schemaLink": "https://*",
            "schemaPublishDate": "2023-04-10T17:19:11.503988200Z"
          }
        ],
        "release": [
          {
            "name": "service1",
            "version": "service_version",
            "isConsumer": true,
            "expectationLink": "https://*",
            "expectationPublishDate": "2023-04-10T17:19:11.503988200Z",
            "isProducer": true,
            "schemaLink": "https://*",
            "schemaPublishDate": "2023-04-10T17:19:11.503988200Z"
          }
        ]
      },
      "validationHistory": [
        {
          "id": 1,
          "date": "2023-04-10T17:19:11.503988200Z",
          "releaseLink": "release_version",
          "status": "SUCCESS/FAILED/IN_PROGRESS/CANCELLED",
          "errorCount": 4
        }
      ]
    }
  ]
}
```
Новые ручки:
1. Получить информацию о всех стендах (стенды отсортированы по имени)

> запрос: `GET /api/stands`
> Статус: 200
> возвращаемая структура:
> ```
>  [
>     {
>       "name": "stand1",
>       "isRelease": false
>     }
>  ]
> ```

2. Получить информацию о статусе стенда:

> запрос: `GET /api/stands/{standName}`
> PathParam: standName (имя стенда с которого нужно получить метаинформацию о сервисах) 
> Статус: 200
> возвращаемая структура:
> ```
>  {
>       "name": "stand1",
>       "isRelease": false,
>       "releaseLink": "release_version",
>       "services": {
>         "stand": [
>           {
>             "name": "service1",
>             "version": "service_version",
>             "isConsumer": true,
>             "expectationLink": "https://*",
>             "expectationPublishDate": "2023-04-10T17:19:11.503988200Z",
>             "isProducer": true,
>             "schemaLink": "https://*",
>             "schemaPublishDate": "2023-04-10T17:19:11.503988200Z"
>           }
>         ],
>         "release": [
>           {
>             "name": "service1",
>             "version": "service_version",
>             "isConsumer": true,
>             "expectationLink": "https://*",
>             "expectationPublishDate": "2023-04-10T17:19:11.503988200Z",
>             "isProducer": true,
>             "schemaLink": "https://*",
>             "schemaPublishDate": "2023-04-10T17:19:11.503988200Z"
>           }
>         ]
>       }
>     }
> ```
> В случае если стенда не существует: 404

3. Получить историю валидаций (валидации отсортированы по дате)

> запрос: `GET /api/stand/{standName}/validations?sizeLimit={sizeLimit}`
> PathParam: standName (имя стенда на котором запускается валидация) 
> QueryParam: sizeLimit (максимальное число возвращаемых валидаций) 
> Статус: 200
> возвращаемая структура: 
> ```
> [
>       {
>         "id": 1,
>         "date": "2023-04-10T17:19:11.503988200Z",
>         "releaseLink": "release_version",
>         "status": "PASSED/FAILED/IN_PROGRESS/RUN_ERROR",
>         "errorCount": 4,
>       }
> ]
> ```
> В случае если стенда не существует: 404

4. Запустить валидацию

> запрос: `POST /api/stand/{{standName}}/validations`
> PathParam: standName (имя стенда на котором запускается валидация) 
> Статус: 202
> В случае если стенда не существует: 404

2023-05-03 17:25 UTC, merged